# Generated by Django 3.1.2 on 2022-05-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20220501_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-articles__scopes__tag'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
