# Generated by Django 3.1.2 on 2022-05-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20220502_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-tag__scopes__main_tag']},
        ),
    ]
